### ISSUE TITLE
DA200

### ISSUE THREAD

**Issue by bartdorlandt** [bambam82/xps13-9360-linux#1]
The DA200 adapters , with USB, VGA, HDMI and ethernet has a limitation in Linux for HDMI.

It only supports up to a maximum resolution of 1680.
No workaround from Dell. 
The USB-C-2-HDMI cable works flawless.

**Comment by manuel-uberti** [comment]
I have a Cable Matters USB-C adapter that works fine:

- Input Host: USB 3.1 Type-C /Thunderbolt 3 Male
- Network: RJ45 Female
- USB-A: USB 3.0 Female
- HDMI: 19 pin Female 
- VGA: 15 pin Female

[This one](http://www.cablematters.com/pc-686-26-usb-c-to-hdmi-vga-ethernet-usb-multiport-4k-uhd-adapter-thunderbolt-3-port-compatible.aspx)

**Comment by bartdorlandt** [comment]
No longer an issue in Ubuntu 18.04. :+1:
